TEXT_SCORE = "Puntaje";
TEXT_SCORE_GAMEOVER = "Puntaje";
TEXT_LEVEL = "Nivel";
TEXT_LEVES = "Niveles"
TEXT_LEVEL_UPPERCASE = "Nivel";
TEXT_COMPLETE = "Completado";
TEXT_CONGRATULATIONS = "Has completado todos los niveles... Felicidades!";
TEXT_HELP_PAGE_1_PC = "Instrucciones";
TEXT_HELP_PAGE_1_MOBILE = "Swipe the paddle to bounce the ball and destroy all the bricks! Grab any falling power-ups to get more points!";
TEXT_DEVELOPED = "DEVELOPED BY";
TEXT_POSICION = "Tu posicion actual es:";
TEXT_PUNTOS_POSICION = "con: ";
TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";
